# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{schoolfinder}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tcocca"]
  s.date = %q{2010-08-25}
  s.description = %q{api wrapper for the education.com schoolfinder}
  s.email = %q{tom.cocca@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rash.rb",
     "lib/schoolfinder.rb",
     "lib/schoolfinder/client.rb",
     "lib/schoolfinder/error.rb",
     "lib/schoolfinder/response.rb",
     "spec/rash_spec.rb",
     "spec/responses/branding_data.json",
     "spec/responses/district_search.json",
     "spec/responses/failure.json",
     "spec/responses/number_of.json",
     "spec/responses/reviews.json",
     "spec/responses/school_search.json",
     "spec/responses/student_diversity.json",
     "spec/responses/student_stats.json",
     "spec/responses/teacher_stats.json",
     "spec/responses/test_rating.json",
     "spec/responses/test_scores.json",
     "spec/schoolfinder/client_spec.rb",
     "spec/schoolfinder/error_spec.rb",
     "spec/schoolfinder_api_key.example.yml",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/tcocca/schoolfinder}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{api wrapper for the education.com schoolfinder}
  s.test_files = [
    "spec/rash_spec.rb",
     "spec/schoolfinder/client_spec.rb",
     "spec/schoolfinder/error_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.6.1"])
      s.add_runtime_dependency(%q<hashie>, [">= 0.3.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<webmock>, [">= 1.3.4"])
    else
      s.add_dependency(%q<httparty>, [">= 0.6.1"])
      s.add_dependency(%q<hashie>, [">= 0.3.1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<webmock>, [">= 1.3.4"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.6.1"])
    s.add_dependency(%q<hashie>, [">= 0.3.1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<webmock>, [">= 1.3.4"])
  end
end

